### ISSUE TITLE
Shipping price parsing problem

### ISSUE THREAD

**Issue by tomer953** [yfrans/amazon-local-currency#2]
Hi,

I think amazon.com (and maybe other domains) updated their shipping price template.

we need to update our `extractPrice()` function.

Demo product:
https://www.amazon.com/gp/product/B083X4VCLB?pf_rd_r=ZS2V02RVRD05ZWBJYHBS&pf_rd_p=6fc81c8c-2a38-41c6-a68a-f78c79e7253f&pd_rd_r=c18de448-e0e3-4518-ba37-f48304c6cebb&pd_rd_w=hYKXB&pd_rd_wg=iNJx8&ref_=pd_gw_unk

![image](https://user-images.githubusercontent.com/1807493/129157381-03bb57ca-f998-4eca-ae6f-3f8885c8599b.png)

this line:
https://github.com/yfrans/amazon-local-currency/blob/ccb913102f3214338977bd6738aa139ca73d864c/script.js#L166

is called with the element:
``` html
<span class="a-size-base a-color-secondary">
$33.16 Import Fees Deposit &amp; <b>FREE Shipping</b> to Israel
</span>
```

leads to a wrong `relevant` variable:
https://github.com/yfrans/amazon-local-currency/blob/ccb913102f3214338977bd6738aa139ca73d864c/script.js#L285
since the `element.querySelectorAll(':not(.a-text-strike)'` not taking the actual shipping price, but the `<b>FREE Shipping</b>` tag

**Comment by yfrans** [comment]
I think we can remove the "relevant" and just take the innerHTML.
In the past, they used to write the old price under the same element as the current price so we had to use this method to extract the correct price. I don't see this behavior anymore.
https://github.com/yfrans/amazon-local-currency/commit/0dcb148af9bdb7d11fd3d539ab00cb81b4247e41

**Comment by tomer953** [comment]
LGTM
thanks
